version: "2"
services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: webapp-frontend
    environment:
      API_URL: http://localhost:8000/api

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: webapp-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 127.0.0.1:8000:80
    container_name: reverse-proxy
    depends_on:
      - web
      - api
